//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIKT.SwmEasy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public Professor()
        {
            this.SeminarWorks = new HashSet<SeminarWork>();
        }
    
        public int ProfessorId { get; set; }
        public string Name { get; set; }
        public System.Guid MembershipUserId { get; set; }
    
        public virtual ICollection<SeminarWork> SeminarWorks { get; set; }
    }
}
