//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIKT.SwmEasy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeminarWorkFile
    {
        public int FileId { get; set; }
        public int SeminarWorkId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string UniqueFileName { get; set; }
        public System.DateTime DateOfUpload { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual SeminarWork SeminarWork { get; set; }
    }
}
