//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIKT.SwmEasy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeminarWork
    {
        public SeminarWork()
        {
            this.SeminarWorkApplications = new HashSet<SeminarWorkApplication>();
            this.SeminarWorkFiles = new HashSet<SeminarWorkFile>();
        }
    
        public int SeminarWorkId { get; set; }
        public int ProfessorId { get; set; }
        public string Title { get; set; }
        public string Abstract { get; set; }
        public string CourseName { get; set; }
        public bool IsStarted { get; set; }
        public bool IsCompleted { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual ICollection<SeminarWorkApplication> SeminarWorkApplications { get; set; }
        public virtual ICollection<SeminarWorkFile> SeminarWorkFiles { get; set; }
    }
}
