//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIKT.SwmEasy.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeminarWorkApplication
    {
        public int ApplicationId { get; set; }
        public int SeminarWorkId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime DateOfApplication { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual SeminarWork SeminarWork { get; set; }
        public virtual Student Student { get; set; }
    }
}
