//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIKT.SwmEasy.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SwmEasyDBEntities : DbContext
    {
        public SwmEasyDBEntities()
            : base("name=SwmEasyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Professor> Professors { get; set; }
        public virtual DbSet<SeminarWork> SeminarWorks { get; set; }
        public virtual DbSet<SeminarWorkApplication> SeminarWorkApplications { get; set; }
        public virtual DbSet<SeminarWorkFile> SeminarWorkFiles { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
